apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    env: devlopment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: krishna
  namespace: development
  labels:
    env: devlopment

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krishna-role
  namespace: development
  labels:
    env: devlopment
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list", "update", "patch", "deletecollection"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krishna-rolebinding
  labels:
    env: devlopment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: krishna-role
subjects:
- kind: ServiceAccount
  name: krishna
  namespace: development
